services:
  db:
    image: postgres:18.1-alpine
    container_name: keycloak_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      - keycloak_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: keycloak_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: abcd
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - keycloak_network
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;grep 'HTTP/1.1 200' <&3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx:latest
    container_name: keycloak_nginx
    ports:
      - "80:80"
    depends_on:
      - keycloak
    networks:
      - keycloak_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  keycloak_db:

networks:
  keycloak_network:
    name: keycloak_network